SELECT * FROM groups WHERE
    group_name LIKE '%gay%'
    OR group_name LIKE '%lesb%'
    OR group_name LIKE '%trans%'
    OR group_name LIKE '%lgbt%'
    OR group_name LIKE '%glbt%'
    OR group_name LIKE '%bisex%'
    OR group_name LIKE '%queer%'
    OR group_name LIKE '%fag%'
    OR group_name REGEXP '\bFTMs?\b'
    OR group_name REGEXP '\bGAM\b'
    OR group_name LIKE '%homo%'
    OR group_name LIKE '%dyke%'
    OR group_name LIKE '\bbi\b'
    OR group_name REGEXP '%bisex%'
    OR group_name REGEXP '\bmtfs?\b'
    OR group_name LIKE '%femme%'
    OR group_name LIKE '%butch%'
    OR group_name REGEXP '\btg\b'
;