SELECT * FROM groups WHERE
    group_name LIKE '%touris%'
    OR group_name LIKE '%swing%'
    OR group_name LIKE '%poly%'
    OR group_name LIKE '%hotwi%'
    OR group_name LIKE '%cuckold%'
    OR group_name LIKE '%orgy%'
    OR group_name REGEXP 'gang\s?bang'
    OR group_name LIKE '%voyeur%'
    OR group_name LIKE '%exhibit%'
    OR group_name REGEXP 'casual\s?encounter'
    OR group_name LIKE '%FFM%'
    OR group_name LIKE '%FMM%'
    OR group_name LIKE '%MFF%'
    OR group_name LIKE '%MMF%'
    OR group_name REGEXP 'hook(ing)?\s?up'
    OR group_name LIKE '%MFMF%'
    OR group_name LIKE '%swap%'
;