INSERT INTO `directory_city` (id, name, state_id) VALUES(1, 'Birmingham city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(2, 'Decatur city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(3, 'Dothan city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(4, 'Hoover city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(5, 'Huntsville city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(6, 'Mobile city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(7, 'Montgomery city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(8, 'Tuscaloosa city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(9, 'Anchorage municipality', 2);
INSERT INTO `directory_city` (id, name, state_id) VALUES(10, 'Casas Adobes CDP', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(11, 'Catalina Foothills CDP', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(12, 'Chandler city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(13, 'Flagstaff city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(14, 'Gilbert town', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(15, 'Glendale city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(16, 'Mesa city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(17, 'Peoria city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(18, 'Phoenix city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(19, 'Scottsdale city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(20, 'Tempe city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(21, 'Tucson city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(22, 'Yuma city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(23, 'Fayetteville city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(24, 'Fort Smith city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(25, 'Jonesboro city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(26, 'Little Rock city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(27, 'North Little Rock city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(28, 'Pine Bluff city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(29, 'Alameda city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(30, 'Alhambra city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(31, 'Anaheim city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(32, 'Antioch city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(33, 'Apple Valley town', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(34, 'Arcadia city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(35, 'Arden-Arcade CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(36, 'Bakersfield city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(37, 'Baldwin Park city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(38, 'Bellflower city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(39, 'Berkeley city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(40, 'Buena Park city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(41, 'Burbank city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(42, 'Camarillo city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(43, 'Carlsbad city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(44, 'Carson city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(45, 'Castro Valley CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(46, 'Cerritos city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(47, 'Chico city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(48, 'Chino Hills city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(49, 'Chino city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(50, 'Chula Vista city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(51, 'Citrus Heights city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(52, 'Clovis city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(53, 'Compton city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(54, 'Concord city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(55, 'Corona city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(56, 'Costa Mesa city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(57, 'Cupertino city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(58, 'Daly City city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(59, 'Davis city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(60, 'Diamond Bar city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(61, 'Downey city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(62, 'East Los Angeles CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(63, 'El Cajon city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(64, 'El Monte city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(65, 'Elk Grove CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(66, 'Encinitas city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(67, 'Escondido city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(68, 'Fairfield city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(69, 'Florence-Graham CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(70, 'Folsom city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(71, 'Fontana city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(72, 'Fountain Valley city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(73, 'Fremont city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(74, 'Fresno city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(75, 'Fullerton city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(76, 'Garden Grove city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(77, 'Gardena city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(78, 'Glendale city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(79, 'Goleta CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(80, 'Hacienda Heights CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(81, 'Hawthorne city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(82, 'Hayward city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(83, 'Hemet city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(84, 'Hesperia city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(85, 'Huntington Beach city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(86, 'Huntington Park city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(87, 'Inglewood city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(88, 'Irvine city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(89, 'La Habra city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(90, 'La Mesa city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(91, 'Laguna Niguel city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(92, 'Lake Forest city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(93, 'Lakewood city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(94, 'Lancaster city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(95, 'Livermore city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(96, 'Lodi city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(97, 'Long Beach city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(98, 'Los Angeles city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(99, 'Lynwood city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(100, 'Merced city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(101, 'Milpitas city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(102, 'Mission Viejo city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(103, 'Modesto city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(104, 'Montebello city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(105, 'Monterey Park city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(106, 'Moreno Valley city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(107, 'Mountain View city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(108, 'Napa city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(109, 'National City city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(110, 'Newport Beach city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(111, 'Norwalk city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(112, 'Oakland city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(113, 'Oceanside city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(114, 'Ontario city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(115, 'Orange city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(116, 'Oxnard city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(117, 'Palmdale city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(118, 'Palo Alto city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(119, 'Paramount city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(120, 'Pasadena city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(121, 'Petaluma city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(122, 'Pico Rivera city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(123, 'Pittsburg city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(124, 'Pleasanton city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(125, 'Pomona city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(126, 'Rancho Cordova CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(127, 'Rancho Cucamonga city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(128, 'Redding city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(129, 'Redlands city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(130, 'Redondo Beach city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(131, 'Redwood City city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(132, 'Rialto city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(133, 'Richmond city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(134, 'Riverside city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(135, 'Rosemead city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(136, 'Roseville city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(137, 'Sacramento city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(138, 'Salinas city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(139, 'San Bernardino city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(140, 'San Buenaventura (Ventura) city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(141, 'San Diego city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(142, 'San Francisco city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(143, 'San Jose city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(144, 'San Leandro city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(145, 'San Marcos city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(146, 'San Mateo city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(147, 'San Rafael city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(148, 'Santa Ana city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(149, 'Santa Barbara city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(150, 'Santa Clara city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(151, 'Santa Clarita city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(152, 'Santa Cruz city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(153, 'Santa Maria city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(154, 'Santa Monica city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(155, 'Santa Rosa city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(156, 'Santee city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(157, 'Simi Valley city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(158, 'South Gate city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(159, 'South San Francisco city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(160, 'South Whittier CDP', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(161, 'Stockton city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(162, 'Sunnyvale city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(163, 'Temecula city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(164, 'Thousand Oaks city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(165, 'Torrance city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(166, 'Tracy city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(167, 'Turlock city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(168, 'Tustin city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(169, 'Union City city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(170, 'Upland city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(171, 'Vacaville city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(172, 'Vallejo city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(173, 'Victorville city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(174, 'Visalia city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(175, 'Vista city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(176, 'Walnut Creek city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(177, 'West Covina city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(178, 'Westminster city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(179, 'Whittier city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(180, 'Yorba Linda city', 6);
INSERT INTO `directory_city` (id, name, state_id) VALUES(181, 'Arvada city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(182, 'Aurora city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(183, 'Boulder city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(184, 'Colorado Springs city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(185, 'Denver city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(186, 'Fort Collins city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(187, 'Greeley city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(188, 'Highlands Ranch CDP', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(189, 'Lakewood city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(190, 'Longmont city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(191, 'Loveland city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(192, 'Pueblo city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(193, 'Thornton city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(194, 'Westminster city', 8);
INSERT INTO `directory_city` (id, name, state_id) VALUES(195, 'Bridgeport city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(196, 'Bridgeport town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(197, 'Bristol city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(198, 'Bristol town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(199, 'Danbury city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(200, 'Danbury town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(201, 'Fairfield town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(202, 'Greenwich town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(203, 'Hamden town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(204, 'Hartford city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(205, 'Hartford town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(206, 'Manchester town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(207, 'Meriden city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(208, 'Meriden town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(209, 'Milford city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(210, 'Milford town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(211, 'New Britain city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(212, 'New Britain town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(213, 'New Haven city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(214, 'New Haven town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(215, 'Norwalk city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(216, 'Norwalk town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(217, 'Stamford city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(218, 'Stamford town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(219, 'Waterbury city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(220, 'Waterbury town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(221, 'West Hartford CDP', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(222, 'West Hartford town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(223, 'West Haven city', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(224, 'West Haven town', 9);
INSERT INTO `directory_city` (id, name, state_id) VALUES(225, 'Wilmington city', 10);
INSERT INTO `directory_city` (id, name, state_id) VALUES(226, 'Boca Raton city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(227, 'Boynton Beach city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(228, 'Brandon CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(229, 'Cape Coral city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(230, 'Carol City CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(231, 'Clearwater city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(232, 'Coral Springs city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(233, 'Davie town', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(234, 'Daytona Beach city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(235, 'Deerfield Beach city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(236, 'Delray Beach city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(237, 'Deltona city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(238, 'Fort Lauderdale city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(239, 'Fountainbleau CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(240, 'Gainesville city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(241, 'Hialeah city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(242, 'Hollywood city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(243, 'Jacksonville city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(244, 'Kendale Lakes CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(245, 'Kendall CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(246, 'Lakeland city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(247, 'Largo city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(248, 'Lauderhill city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(249, 'Margate city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(250, 'Melbourne city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(251, 'Miami Beach city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(252, 'Miami city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(253, 'Miramar city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(254, 'North Miami city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(255, 'Orlando city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(256, 'Palm Bay city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(257, 'Palm Harbor CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(258, 'Pembroke Pines city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(259, 'Pensacola city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(260, 'Plantation city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(261, 'Pompano Beach city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(262, 'Port St. Lucie city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(263, 'Sarasota city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(264, 'Spring Hill CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(265, 'St. Petersburg city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(266, 'Sunrise city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(267, 'Tallahassee city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(268, 'Tamarac city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(269, 'Tamiami CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(270, 'Tampa city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(271, 'Town ''n'' Country CDP', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(272, 'West Palm Beach city', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(273, 'Albany city', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(274, 'Athens-Clarke County', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(275, 'Atlanta city', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(276, 'Augusta-Richmond County', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(277, 'Columbus city', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(278, 'Macon city', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(279, 'Marietta city', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(280, 'Roswell city', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(281, 'Sandy Springs CDP', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(282, 'Savannah city', 13);
INSERT INTO `directory_city` (id, name, state_id) VALUES(283, 'Honolulu CDP', 15);
INSERT INTO `directory_city` (id, name, state_id) VALUES(284, 'Boise City city', 16);
INSERT INTO `directory_city` (id, name, state_id) VALUES(285, 'Idaho Falls city', 16);
INSERT INTO `directory_city` (id, name, state_id) VALUES(286, 'Nampa city', 16);
INSERT INTO `directory_city` (id, name, state_id) VALUES(287, 'Pocatello city', 16);
INSERT INTO `directory_city` (id, name, state_id) VALUES(288, 'Arlington Heights village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(289, 'Aurora city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(290, 'Berwyn city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(291, 'Bloomington city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(292, 'Bolingbrook village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(293, 'Champaign city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(294, 'Chicago city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(295, 'Cicero town', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(296, 'Decatur city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(297, 'Des Plaines city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(298, 'Elgin city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(299, 'Evanston city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(300, 'Joliet city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(301, 'Mount Prospect village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(302, 'Naperville city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(303, 'Oak Lawn village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(304, 'Oak Park village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(305, 'Orland Park village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(306, 'Palatine village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(307, 'Peoria city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(308, 'Rockford city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(309, 'Schaumburg village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(310, 'Skokie village', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(311, 'Springfield city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(312, 'Waukegan city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(313, 'Wheaton city', 17);
INSERT INTO `directory_city` (id, name, state_id) VALUES(314, 'Anderson city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(315, 'Bloomington city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(316, 'Elkhart city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(317, 'Evansville city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(318, 'Fort Wayne city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(319, 'Gary city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(320, 'Hammond city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(321, 'Indianapolis city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(322, 'Lafayette city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(323, 'Muncie city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(324, 'South Bend city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(325, 'Terre Haute city', 18);
INSERT INTO `directory_city` (id, name, state_id) VALUES(326, 'Ames city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(327, 'Cedar Rapids city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(328, 'Council Bluffs city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(329, 'Davenport city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(330, 'Des Moines city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(331, 'Dubuque city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(332, 'Iowa City city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(333, 'Sioux City city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(334, 'Waterloo city', 19);
INSERT INTO `directory_city` (id, name, state_id) VALUES(335, 'Kansas City city', 20);
INSERT INTO `directory_city` (id, name, state_id) VALUES(336, 'Lawrence city', 20);
INSERT INTO `directory_city` (id, name, state_id) VALUES(337, 'Olathe city', 20);
INSERT INTO `directory_city` (id, name, state_id) VALUES(338, 'Overland Park city', 20);
INSERT INTO `directory_city` (id, name, state_id) VALUES(339, 'Topeka city', 20);
INSERT INTO `directory_city` (id, name, state_id) VALUES(340, 'Wichita city', 20);
INSERT INTO `directory_city` (id, name, state_id) VALUES(341, 'Lexington-Fayette', 21);
INSERT INTO `directory_city` (id, name, state_id) VALUES(342, 'Louisville city', 21);
INSERT INTO `directory_city` (id, name, state_id) VALUES(343, 'Owensboro city', 21);
INSERT INTO `directory_city` (id, name, state_id) VALUES(344, 'Baton Rouge city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(345, 'Bossier City city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(346, 'Kenner city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(347, 'Lafayette city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(348, 'Lake Charles city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(349, 'Metairie CDP', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(350, 'Monroe city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(351, 'New Orleans city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(352, 'Shreveport city', 22);
INSERT INTO `directory_city` (id, name, state_id) VALUES(353, 'Portland city', 23);
INSERT INTO `directory_city` (id, name, state_id) VALUES(354, 'Aspen Hill CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(355, 'Baltimore city', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(356, 'Bethesda CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(357, 'Bowie city', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(358, 'Columbia CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(359, 'Dundalk CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(360, 'Ellicott City CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(361, 'Frederick city', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(362, 'Gaithersburg city', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(363, 'Germantown CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(364, 'Silver Spring CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(365, 'Towson CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(366, 'Wheaton-Glenmont CDP', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(367, 'Boston city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(368, 'Brockton city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(369, 'Brookline CDP', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(370, 'Brookline town', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(371, 'Cambridge city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(372, 'Chicopee city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(373, 'Fall River city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(374, 'Framingham CDP', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(375, 'Framingham town', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(376, 'Haverhill city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(377, 'Lawrence city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(378, 'Lowell city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(379, 'Lynn city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(380, 'Malden city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(381, 'Medford city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(382, 'New Bedford city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(383, 'Newton city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(384, 'Plymouth town', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(385, 'Quincy city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(386, 'Somerville city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(387, 'Springfield city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(388, 'Taunton city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(389, 'Waltham city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(390, 'Weymouth CDP', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(391, 'Weymouth town', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(392, 'Worcester city', 25);
INSERT INTO `directory_city` (id, name, state_id) VALUES(393, 'Ann Arbor city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(394, 'Battle Creek city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(395, 'Canton CDP', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(396, 'Canton township', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(397, 'Clinton CDP', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(398, 'Clinton township', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(399, 'Dearborn Heights city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(400, 'Dearborn city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(401, 'Detroit city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(402, 'Farmington Hills city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(403, 'Flint city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(404, 'Grand Rapids city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(405, 'Kalamazoo city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(406, 'Lansing city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(407, 'Livonia city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(408, 'Macomb township', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(409, 'Pontiac city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(410, 'Redford CDP', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(411, 'Redford township', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(412, 'Rochester Hills city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(413, 'Royal Oak city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(414, 'Saginaw city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(415, 'Shelby CDP', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(416, 'Shelby charter township', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(417, 'Southfield city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(418, 'St. Clair Shores city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(419, 'Sterling Heights city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(420, 'Taylor city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(421, 'Troy city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(422, 'Warren city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(423, 'Waterford CDP', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(424, 'Waterford township', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(425, 'West Bloomfield Township CDP', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(426, 'West Bloomfield township', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(427, 'Westland city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(428, 'Wyoming city', 26);
INSERT INTO `directory_city` (id, name, state_id) VALUES(429, 'Bloomington city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(430, 'Brooklyn Park city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(431, 'Burnsville city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(432, 'Coon Rapids city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(433, 'Duluth city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(434, 'Eagan city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(435, 'Eden Prairie city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(436, 'Maple Grove city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(437, 'Minneapolis city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(438, 'Minnetonka city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(439, 'Plymouth city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(440, 'Rochester city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(441, 'St. Cloud city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(442, 'St. Paul city', 27);
INSERT INTO `directory_city` (id, name, state_id) VALUES(443, 'Biloxi city', 29);
INSERT INTO `directory_city` (id, name, state_id) VALUES(444, 'Gulfport city', 29);
INSERT INTO `directory_city` (id, name, state_id) VALUES(445, 'Jackson city', 29);
INSERT INTO `directory_city` (id, name, state_id) VALUES(446, 'Columbia city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(447, 'Florissant city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(448, 'Independence city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(449, 'Kansas City city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(450, 'Lee''s Summit city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(451, 'Springfield city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(452, 'St. Charles city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(453, 'St. Joseph city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(454, 'St. Louis city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(455, 'St. Peters city', 28);
INSERT INTO `directory_city` (id, name, state_id) VALUES(456, 'Billings city', 30);
INSERT INTO `directory_city` (id, name, state_id) VALUES(457, 'Great Falls city', 30);
INSERT INTO `directory_city` (id, name, state_id) VALUES(458, 'Missoula city', 30);
INSERT INTO `directory_city` (id, name, state_id) VALUES(459, 'Lincoln city', 31);
INSERT INTO `directory_city` (id, name, state_id) VALUES(460, 'Omaha city', 31);
INSERT INTO `directory_city` (id, name, state_id) VALUES(461, 'Carson City', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(462, 'Henderson city', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(463, 'Las Vegas city', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(464, 'North Las Vegas city', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(465, 'Paradise CDP', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(466, 'Reno city', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(467, 'Sparks city', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(468, 'Spring Valley CDP', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(469, 'Sunrise Manor CDP', 32);
INSERT INTO `directory_city` (id, name, state_id) VALUES(470, 'Manchester city', 33);
INSERT INTO `directory_city` (id, name, state_id) VALUES(471, 'Nashua city', 33);
INSERT INTO `directory_city` (id, name, state_id) VALUES(472, 'Bayonne city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(473, 'Brick township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(474, 'Camden city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(475, 'Cherry Hill township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(476, 'Clifton city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(477, 'Dover township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(478, 'East Orange city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(479, 'Edison CDP', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(480, 'Edison township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(481, 'Elizabeth city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(482, 'Franklin township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(483, 'Gloucester township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(484, 'Hamilton township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(485, 'Irvington CDP', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(486, 'Irvington township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(487, 'Jersey City city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(488, 'Lakewood township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(489, 'Middletown township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(490, 'Newark city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(491, 'North Bergen township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(492, 'Old Bridge township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(493, 'Parsippany-Troy Hills township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(494, 'Passaic city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(495, 'Paterson city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(496, 'Piscataway township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(497, 'Toms River CDP', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(498, 'Trenton city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(499, 'Union CDP', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(500, 'Union City city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(501, 'Union township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(502, 'Vineland city', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(503, 'Wayne CDP', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(504, 'Wayne township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(505, 'Woodbridge township', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(506, 'Albuquerque city', 35);
INSERT INTO `directory_city` (id, name, state_id) VALUES(507, 'Las Cruces city', 35);
INSERT INTO `directory_city` (id, name, state_id) VALUES(508, 'Rio Rancho city', 35);
INSERT INTO `directory_city` (id, name, state_id) VALUES(509, 'Santa Fe city', 35);
INSERT INTO `directory_city` (id, name, state_id) VALUES(510, 'Albany city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(511, 'Amherst town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(512, 'Babylon town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(513, 'Brentwood CDP', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(514, 'Bronx borough', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(515, 'Brookhaven town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(516, 'Brooklyn borough', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(517, 'Buffalo city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(518, 'Cheektowaga CDP', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(519, 'Cheektowaga town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(520, 'Clarkstown town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(521, 'Clay town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(522, 'Colonie town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(523, 'Greece town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(524, 'Greenburgh town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(525, 'Hamburg town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(526, 'Hempstead town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(527, 'Hempstead village', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(528, 'Huntington town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(529, 'Irondequoit CDP', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(530, 'Irondequoit town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(531, 'Islip town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(532, 'Levittown CDP', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(533, 'Manhattan borough', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(534, 'Mount Vernon city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(535, 'New Rochelle city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(536, 'New York city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(537, 'Niagara Falls city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(538, 'North Hempstead town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(539, 'Oyster Bay town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(540, 'Queens borough', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(541, 'Ramapo town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(542, 'Rochester city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(543, 'Schenectady city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(544, 'Smithtown town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(545, 'Southampton town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(546, 'Staten Island borough', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(547, 'Syracuse city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(548, 'Tonawanda CDP', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(549, 'Tonawanda town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(550, 'Union town', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(551, 'Utica city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(552, 'White Plains city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(553, 'Yonkers city', 36);
INSERT INTO `directory_city` (id, name, state_id) VALUES(554, 'Asheville city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(555, 'Cary town', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(556, 'Charlotte city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(557, 'Concord city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(558, 'Durham city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(559, 'Fayetteville city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(560, 'Gastonia city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(561, 'Greensboro city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(562, 'Greenville city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(563, 'High Point city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(564, 'Jacksonville city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(565, 'Raleigh city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(566, 'Rocky Mount city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(567, 'Wilmington city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(568, 'Winston-Salem city', 37);
INSERT INTO `directory_city` (id, name, state_id) VALUES(569, 'Bismarck city', 38);
INSERT INTO `directory_city` (id, name, state_id) VALUES(570, 'Fargo city', 38);
INSERT INTO `directory_city` (id, name, state_id) VALUES(571, 'Akron city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(572, 'Canton city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(573, 'Cincinnati city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(574, 'Cleveland city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(575, 'Columbus city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(576, 'Dayton city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(577, 'Elyria city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(578, 'Euclid city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(579, 'Hamilton city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(580, 'Kettering city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(581, 'Lakewood city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(582, 'Lorain city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(583, 'Mentor city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(584, 'Middletown city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(585, 'Parma city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(586, 'Springfield city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(587, 'Toledo city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(588, 'Youngstown city', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(589, 'Broken Arrow city', 40);
INSERT INTO `directory_city` (id, name, state_id) VALUES(590, 'Edmond city', 40);
INSERT INTO `directory_city` (id, name, state_id) VALUES(591, 'Lawton city', 40);
INSERT INTO `directory_city` (id, name, state_id) VALUES(592, 'Midwest City city', 40);
INSERT INTO `directory_city` (id, name, state_id) VALUES(593, 'Norman city', 40);
INSERT INTO `directory_city` (id, name, state_id) VALUES(594, 'Oklahoma City city', 40);
INSERT INTO `directory_city` (id, name, state_id) VALUES(595, 'Tulsa city', 40);
INSERT INTO `directory_city` (id, name, state_id) VALUES(596, 'Beaverton city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(597, 'Bend city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(598, 'Eugene city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(599, 'Gresham city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(600, 'Hillsboro city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(601, 'Medford city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(602, 'Portland city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(603, 'Salem city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(604, 'Springfield city', 41);
INSERT INTO `directory_city` (id, name, state_id) VALUES(605, 'Abington township', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(606, 'Allentown city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(607, 'Bensalem township', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(608, 'Bethlehem city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(609, 'Bristol township', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(610, 'Erie city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(611, 'Lancaster city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(612, 'Levittown CDP', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(613, 'Lower Merion township', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(614, 'Millcreek township', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(615, 'Philadelphia city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(616, 'Pittsburgh city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(617, 'Reading city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(618, 'Scranton city', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(619, 'Upper Darby township', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(620, 'Cranston city', 44);
INSERT INTO `directory_city` (id, name, state_id) VALUES(621, 'Pawtucket city', 44);
INSERT INTO `directory_city` (id, name, state_id) VALUES(622, 'Providence city', 44);
INSERT INTO `directory_city` (id, name, state_id) VALUES(623, 'Warwick city', 44);
INSERT INTO `directory_city` (id, name, state_id) VALUES(624, 'Charleston city', 45);
INSERT INTO `directory_city` (id, name, state_id) VALUES(625, 'Columbia city', 45);
INSERT INTO `directory_city` (id, name, state_id) VALUES(626, 'Greenville city', 45);
INSERT INTO `directory_city` (id, name, state_id) VALUES(627, 'North Charleston city', 45);
INSERT INTO `directory_city` (id, name, state_id) VALUES(628, 'Rapid City city', 46);
INSERT INTO `directory_city` (id, name, state_id) VALUES(629, 'Sioux Falls city', 46);
INSERT INTO `directory_city` (id, name, state_id) VALUES(630, 'Chattanooga city', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(631, 'Clarksville city', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(632, 'Jackson city', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(633, 'Johnson City city', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(634, 'Knoxville city', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(635, 'Memphis city', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(636, 'Murfreesboro city', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(637, 'Nashville-Davidson', 47);
INSERT INTO `directory_city` (id, name, state_id) VALUES(638, 'Abilene city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(639, 'Amarillo city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(640, 'Arlington city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(641, 'Austin city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(642, 'Baytown city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(643, 'Beaumont city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(644, 'Brownsville city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(645, 'Bryan city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(646, 'Carrollton city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(647, 'College Station city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(648, 'Corpus Christi city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(649, 'Dallas city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(650, 'Denton city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(651, 'El Paso city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(652, 'Flower Mound town', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(653, 'Fort Worth city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(654, 'Galveston city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(655, 'Garland city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(656, 'Grand Prairie city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(657, 'Harlingen city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(658, 'Houston city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(659, 'Irving city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(660, 'Killeen city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(661, 'Laredo city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(662, 'Lewisville city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(663, 'Longview city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(664, 'Lubbock city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(665, 'McAllen city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(666, 'McKinney city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(667, 'Mesquite city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(668, 'Midland city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(669, 'Missouri City city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(670, 'North Richland Hills city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(671, 'Odessa city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(672, 'Pasadena city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(673, 'Plano city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(674, 'Port Arthur city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(675, 'Richardson city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(676, 'Round Rock city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(677, 'San Angelo city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(678, 'San Antonio city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(679, 'Sugar Land city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(680, 'Temple city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(681, 'The Woodlands CDP', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(682, 'Tyler city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(683, 'Victoria city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(684, 'Waco city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(685, 'Wichita Falls city', 48);
INSERT INTO `directory_city` (id, name, state_id) VALUES(686, 'Layton city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(687, 'Ogden city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(688, 'Orem city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(689, 'Provo city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(690, 'Salt Lake City city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(691, 'Sandy city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(692, 'Taylorsville city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(693, 'West Jordan city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(694, 'West Valley City city', 49);
INSERT INTO `directory_city` (id, name, state_id) VALUES(695, 'Alexandria city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(696, 'Annandale CDP', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(697, 'Arlington CDP', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(698, 'Burke CDP', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(699, 'Chesapeake city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(700, 'Dale City CDP', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(701, 'Hampton city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(702, 'Lynchburg city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(703, 'Newport News city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(704, 'Norfolk city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(705, 'Portsmouth city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(706, 'Reston CDP', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(707, 'Richmond city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(708, 'Roanoke city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(709, 'Suffolk city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(710, 'Virginia Beach city', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(711, 'Virginia', 50);
INSERT INTO `directory_city` (id, name, state_id) VALUES(712, 'Bellevue city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(713, 'Bellingham city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(714, 'Everett city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(715, 'Federal Way city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(716, 'Kennewick city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(717, 'Kent city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(718, 'Lakewood city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(719, 'Renton city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(720, 'Seattle city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(721, 'Shoreline city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(722, 'Spokane city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(723, 'Tacoma city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(724, 'Vancouver city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(725, 'Yakima city', 53);
INSERT INTO `directory_city` (id, name, state_id) VALUES(726, 'Charleston city', 54);
INSERT INTO `directory_city` (id, name, state_id) VALUES(727, 'Huntington city', 54);
INSERT INTO `directory_city` (id, name, state_id) VALUES(728, 'Appleton city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(729, 'Eau Claire city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(730, 'Green Bay city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(731, 'Janesville city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(732, 'Kenosha city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(733, 'La Crosse city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(734, 'Madison city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(735, 'Milwaukee city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(736, 'Oshkosh city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(737, 'Racine city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(738, 'Sheboygan city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(739, 'Waukesha city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(740, 'West Allis city', 55);
INSERT INTO `directory_city` (id, name, state_id) VALUES(741, 'Cheyenne city', 56);
INSERT INTO `directory_city` (id, name, state_id) VALUES(742, 'Athens city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(743, 'Fultondale city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(744, 'Jasper city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(745, 'Mccalla town', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(746, 'Courtland town', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(747, 'Muscle Shoals city', 1);
INSERT INTO `directory_city` (id, name, state_id) VALUES(748, 'Fairbanks city', 2);
INSERT INTO `directory_city` (id, name, state_id) VALUES(749, 'Anchorage city', 2);
INSERT INTO `directory_city` (id, name, state_id) VALUES(750, 'Bullhead City', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(751, 'Queen Creek town', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(752, 'El Mirage town', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(753, 'Surprise city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(754, 'Prescott city', 4);
INSERT INTO `directory_city` (id, name, state_id) VALUES(755, 'Malvern city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(756, 'Benton city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(757, 'Hot springs town', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(758, 'Romance city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(759, 'Walcott town', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(760, 'Ward city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(761, 'Paragould city', 5);
INSERT INTO `directory_city` (id, name, state_id) VALUES(762, 'New Port Richey', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(763, 'Tampa Bay', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(764, 'Jupiter', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(765, 'Riverview', 12);
INSERT INTO `directory_city` (id, name, state_id) VALUES(766, 'Lexington', 45);
INSERT INTO `directory_city` (id, name, state_id) VALUES(767, 'Spartanburg', 45);
INSERT INTO `directory_city` (id, name, state_id) VALUES(768, 'Zanesville', 39);
INSERT INTO `directory_city` (id, name, state_id) VALUES(769, 'Catonsville', 24);
INSERT INTO `directory_city` (id, name, state_id) VALUES(770, 'Atlantic City', 34);
INSERT INTO `directory_city` (id, name, state_id) VALUES(771, 'Washington', 57);
INSERT INTO `directory_city` (id, name, state_id) VALUES(772, 'Wilkes-Barre', 42);
INSERT INTO `directory_city` (id, name, state_id) VALUES(773, 'Euless', 48);
