INSERT INTO `directory_state` (id, usps_name, name) VALUES(1, 'AL', 'Alabama');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(2, 'AK', 'Alaska');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(4, 'AZ', 'Arizona');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(5, 'AR', 'Arkansas');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(6, 'CA', 'California');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(8, 'CO', 'Colorado');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(9, 'CT', 'Connecticut');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(10, 'DE', 'Delaware');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(12, 'FL', 'Florida');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(13, 'GA', 'Georgia');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(15, 'HI', 'Hawaii');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(16, 'ID', 'Idaho');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(17, 'IL', 'Illinois');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(18, 'IN', 'Indiana');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(19, 'IA', 'Iowa');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(20, 'KS', 'Kansas');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(21, 'KY', 'Kentucky');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(22, 'LA', 'Louisiana');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(23, 'ME', 'Maine');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(24, 'MD', 'Maryland');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(25, 'MA', 'Massachusetts');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(26, 'MI', 'Michigan');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(27, 'MN', 'Minnesota');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(28, 'MO', 'Missouri');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(29, 'MS', 'Mississippi');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(30, 'MT', 'Montana');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(31, 'NE', 'Nebraska');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(32, 'NV', 'Nevada');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(33, 'NH', 'New Hampshire');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(34, 'NJ', 'New Jersey');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(35, 'NM', 'New Mexico');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(36, 'NY', 'New York');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(37, 'NC', 'North Carolina');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(38, 'ND', 'North Dakota');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(39, 'OH', 'Ohio');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(40, 'OK', 'Oklahoma');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(41, 'OR', 'Oregon');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(42, 'PA', 'Pennsylvania');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(44, 'RI', 'Rhode Island');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(45, 'SC', 'South Carolina');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(46, 'SD', 'South Dakota');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(47, 'TN', 'Tennessee');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(48, 'TX', 'Texas');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(49, 'UT', 'Utah');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(50, 'VT', 'Vermont');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(51, 'VA', 'Virginia');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(53, 'WA', 'Washington');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(54, 'WV', 'West Virginia');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(55, 'WI', 'Wisconsin');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(56, 'WY', 'Wyoming');
INSERT INTO `directory_state` (id, usps_name, name) VALUES(57, 'DC', 'Washington, DC');
